### ISSUE TITLE
Can't load "xlsx" package because of "rJava" issues

### ISSUE THREAD

**Issue by AustinGratton** [silvialiverani/PReMiuM-R-package#2]
When I try to load the "xlsx" package it gives me the following error:

> Loading required package: rJava
> Error : .onLoad failed in loadNamespace() for 'rJava', details:
>   call: fun(libname, pkgname)
>   error: No CurrentVersion entry in Software/JavaSoft registry! Try re-installing Java and make sure R and Java have matching architectures.
> Error: package ‘rJava’ could not be loaded

However, I am able to run what i need and the plots work fine, etc. I got it from the old code. Is this package still necessary?

**Comment by silvialiverani** [comment]
Hi, is this issue at all related to the package PReMiuM, which this is the repository for?

**Comment by AustinGratton** [comment]
Yes, in the old code that Dr. Stapleton wanted me and Thomas to update, this was one of the packages loaded before running everything.

**Comment by silvialiverani** [comment]
So it wasn't uploaded within PReMiuM - was it? Was is loaded alongside PReMiuM? In the latter case it was loaded to do something else outside of PReMiuM. It seems to be a package that links with Excel and I don't think I have ever used it. Maybe it is used to load or manipulate the data?

**Comment by AustinGratton** [comment]
Thank you. It runs fine without it, so I will discard it.
