### ISSUE TITLE
Slight change to PReMiuM manual. Section 6

### ISSUE THREAD

**Issue by AustinGratton** [silvialiverani/PReMiuM-R-package#3]
I ran the sample code in section 6 of the manual and got different outcomes. I realized it was because the input sample data is generated with a random seed. If there is a set.seed() before 
`inputs <- generateSampleDataFile(clusSummaryNormalDiscrete())`
It will ensure consistent outcomes with the manual.

**Comment by silvialiverani** [comment]
Thanks for this - I have added the set.seed() command.
