### ISSUE TITLE
Small typo in Section 6 of the PReMiuM manual.

### ISSUE THREAD

**Issue by AustinGratton** [silvialiverani/PReMiuM-R-package#4]
In the sample code, at the bottom of page 11, there is an extra '#' that cancels out the colors for the violin plot, making the clusters different colors than the previous plots.

`> p#+scale_fill_brewer(palette="Set1")`

should be

`> p+scale_fill_brewer(palette="Set1")`

Sorry if this was intentional!

**Comment by silvialiverani** [comment]
Thanks for this - fixed.
