### ISSUE TITLE
error generating trying to run plotRiskProfile

### ISSUE THREAD

**Issue by dhbrand** [silvialiverani/PReMiuM-R-package#6]
I'm having an issue where I get an error when I try to generate the risk profile plot.  
`> clusterOrderObj<-plotRiskProfile(riskProfileOb,"summary.png")
Error in quantile.default(newX[, i], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE`

I looked in the output from `riskProfileOb <- calcAvgRiskAndProfile(clusts)` and can see only the profileMu array with NaN's.  But I cross-referenced against a script that I am able to run all the way through and it also has NaN's in the same place.  

Any ideas what might be causing this error?

Script below 
```
###job script for batch submission

#setwd("~/Stapleton_Lab/Projects/Premium/R work/")
library(PReMiuM)

dat <- read.csv("../hybrid.csv", row.names = 1,header=TRUE)

##changed Geno to Pedi and need update csv on stampede2
dat$Pedi<-as.character(dat$Pedi)
##subsetting for only min max cov's
numericVars <- c(grep("min",names(dat)) , grep("max",names(dat)))
#numericVars <- which(sapply(dat, class)=='numeric' & names(dat) != 'Yield')
categoricalVars <- which(sapply(dat, class)=='character' & names(dat) != 'Yield')

system.time({
    
    mod <- profRegr(covName, outcome = 'Yield', nSweeps = 10, nBurn = 1,
                    yModel = 'Normal', xModel = "Mixed",
                    #nCovariates = 2,
                    #fixedEffectsNames = 'yield',
                    discreteCovs = c(names(dat[categoricalVars])),
                    continuousCovs = c(names(dat[numericVars])),
                    data = dat)
})

calcDists <- calcDissimilarityMatrix(mod)

clusts <- calcOptimalClustering(calcDists,maxNClusters = 4)

riskProfileOb <- calcAvgRiskAndProfile(clusts)

clusterOrderObj<-plotRiskProfile(riskProfileOb,"summary.png")


```

Console output below
```
 [997] "Replacing level Z013E0028/LH82 with 996"                                       
 [998] "Replacing level Z013E0028/PHZ51 with 997"                                      
 [999] "Replacing level Z013E0032/LH185 with 998"                                      
[1000] "Replacing level Z013E0034/LH185 with 999"                                      
 [ reached getOption("max.print") -- omitted 156 entries ]
Random number seed: 1516047350
Sweep: 1
   user  system elapsed 
 44.337   5.899  50.671 
> calcDists <- calcDissimilarityMatrix(mod)
Stage 1:1 samples out of 10
Stage 2:1 samples out of 10
> clusts <- calcOptimalClustering(calcDists,maxNClusters = 4)
Max no of possible clusters: 4 
Trying 2 clusters
Trying 3 clusters
Trying 4 clusters
> riskProfileOb <- calcAvgRiskAndProfile(clusts)
Processing sweep 1 of  10 
> clusterOrderObj<-plotRiskProfile(riskProfileOb,"summary.png")
Error in quantile.default(newX[, i], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE
>
```

**Comment by silvialiverani** [comment]
Could you send me a simple case when this happens to try to replicate it on my computer and debug?

**Comment by dhbrand** [comment]
Well I figured out how to get my dataset to run and produce the plot.  There were no missing values in the data but some of the minimum weather variables were zero.  I took out any covariates with values containing '0' and was able to produce the plot.  The error message generating says its because of NaN's or missing values but evidently zero's are a problem for covariate values as well.  So going forward I will be removing value of '0' unless you think it should be able to run with them still in the data.

**Comment by dhbrand** [comment]
Evidently it's not generating because of zero values.  I ran a batch job subsetting a dataframe by month and 3 of the 10 plots generating only partially and the rest generated completely.  I have all the files and outputs on my Coverse DataStore.  Might be the easiest way for me to share so much data.

**Comment by dhbrand** [comment]
I ran a traceback and this is where its generating the error.  It looks like line 2019 is the first occurrence of `apply(muMat, 2, quantile, 0.05)`.

```
Selection: 3
Browse[4]> n

Enter a frame number, or 0 to exit   

1: plotRiskProfile(riskProfileOb, "dec.png")
2: apply(muMat, 2, quantile, 0.05)
3: FUN(newX[, i], ...)
4: quantile.default(newX[, i], ...)

Selection: 4
Called from: stop("missing values and NaN's not allowed if 'na.rm' is FALSE")
Browse[3]> 
```

**Comment by dhbrand** [comment]
I kept digging into the code and discovered the error is actually generating at 2 places.  The aforementioned quantile function on the muMat as well as sigmaMat.  I kept tracing back and finally realized the output_mu.txt and output_sigma.txt have NA's and thats where the error is originating. I've been looking at your journal article on Premium trying to discover why these NA values are generating.  The statistics has me a little lost.  Do you have any ideas or suggestions?

**Comment by silvialiverani** [comment]
The issue was that one of the variables was constant. Variables should not be included if they are constants.
