### ISSUE TITLE
profRegr crashes after random seed

### ISSUE THREAD

**Issue by ck37** [silvialiverani/PReMiuM-R-package#7]
Hello,

I'm interested in trying out the package but am running into an issue where, while running profRegr(), RStudio crashes immediately after outputting the "random number seed" line. This is on Windows 10, RStudio 1.1.383, R 3.4.2, and PReMiuM package version 3.1.6.

My data consists of a binary outcome variable, 12 exposure variables (covNames), and 3 fixed effect variables. There is some missingness in the exposure variables but not in the fixed effect variables.

Here is my code leading up to the call:
```r
n_burn = 1000
n_sweeps = 10000
n_after_thin = 100
(n_filter = max(round(n_sweeps / n_after_thin), 1))

bpr = profRegr(yModel = "Binomial",
               xModel = "Discrete",
               data = data,
               outcome = var_outcome,
               outcomeT = 1,
               covNames = vars_exposures,
               fixedEffectsNames = vars_control,
               nBurn = n_burn,
               nSweeps = n_sweeps,
               nFilter = n_filter,
               varSelectType = "Continuous",
               output = "output/bpr",
               nClusInit = 20)
```

Any suggestions on where I might be making a mistake, or is there additional information that would be helpful? I can try to come up with a reproducible example if that would help.

Thanks,
Chris

**Comment by silvialiverani** [comment]
Dear Chris, 
Thanks for this. Could you send me a simple example (including data) so that I can try testing this and figuring out what the problem might be?
